# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
     file_directory: '%kernel.project_dir%/public/uploads'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Service\Uploader:
        arguments:
            $uploadedFileDirectory: '%file_directory%'

    App\EventListener\CustomEventListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response } 

    App\EventListener\IpLoggerEventListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request }
    
    App\EventListener\TvShowUpdateLogger:
        # Je rajoute un "comportement" particullier sur mon service
        tags:
            # je precise qu'il doit etre contacté par le gestionnaire d'evenements de Doctrine
            # lorsqu'il y a un evnemetn Update sur une entité TvShow on executera la methode onTvShowUpdate de ce service
            - { name: doctrine.orm.entity_listener, event: postUpdate, entity: App\Entity\TvShow, method: 'onTvShowUpdate' } 
